version: '3.7'
networks:
    sampleservice_net:
      name: 'sampleservice_net' 

services:
    aspnet:
        build: 
          dockerfile: ./Sample.Service/Dockerfile
          context: .
        restart: always
        container_name: 'sampleservice_local'
        ports:
          - 8000:80
        working_dir: '/app'
        networks:
          - sampleservice_net   

    db:
        image: 'postgres:12.1'
        container_name: 'sampleservice_local_db'
        restart: always
        networks:
            - sampleservice_net    
        environment:
            POSTGRES_DB: interview_rhenus
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 9000:5432
    
    adminer:
        image: adminer
        restart: always
        networks:
          - sampleservice_net    
        ports:
            - 8080:8080
        depends_on:
          - db
